# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9f89f69758e199eb17fd8d3456b84e9bd06e3abaf0500c1109dc3ff1e28b1ba25aec6fe34b42489ce6c63572a8de8a0d16dfcc4e26172018688cc2a19c61a8

test:
  secret_key_base: 91aeddedfb3e3f1fb2a183918ada06ecb8839fb4631ad40a5dee716560a002d1010a55169d81ff8280b29bde0df74d667f913ad5704d7aa626af9d0af9171c8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
